on:
  push:
    branches: [ main ]
    
name: Build .Net


jobs:
  build:
    name: Build
    runs-on: windows-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --output "dotnet-release/"
      
    - uses: actions/upload-artifact@v2
      id: buildPackege
      with:
        name: Release
        path: "dotnet-release/"
      
    - name: Create Tag Build
      uses: mydea/action-tag-date-version@v20
      id: action-tag-date-version
   
    - name: Release
      uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.action-tag-date-version.outputs.version }}
        tag_name: ${{ steps.action-tag-date-version.outputs.version }}
    
    - name: Upload Release Assets
      uses: wzshiming/action-upload-release-assets@v1
      env:
        GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        RELEASE: "dotnet-release/"
    
