on:
  pull_request:
    branches: [ preview ]
    
name: Build .Net Preview


jobs:
  build:
    name: Build
    runs-on: windows-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --output "dotnet-release/"
      
    - name: Zip Release
      id: buildPackege
      shell: pwsh
      run: Compress-Archive -Path 'dotnet-release\*' -DestinationPath 'dotnet-release\Release.zip'
              
    - name: Create Tag Build
      uses: mydea/action-tag-date-version@v20
      id: action-tag-date-version
      with:
        prerelease: preview

   
    - name: Release
      uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        draft: false
        prerelease: true
        release_name: ${{ steps.action-tag-date-version.outputs.version }}
        tag_name: ${{ steps.action-tag-date-version.outputs.version }}
    
    - name: Upload Release Assets
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dotnet-release/Release.zip
        tag: ${{ steps.action-tag-date-version.outputs.version }}
    
